services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: database
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      DATABASE_URL: 'postgresql://postgres:12345678@db:5432/database'
      JWT_SECRET: 'yoursecret'
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
