apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: 255047008719.dkr.ecr.us-east-1.amazonaws.com/nestjs-app
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nest-app-service
spec:
  type: LoadBalancer
  selector:
    app: nest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
