name: Deploy to Amazon EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
      IMAGE_TAG: ${{ github.sha }} # Usando o SHA do commit como tag de imagem

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $AWS_ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $AWS_ECR_REPOSITORY:$IMAGE_TAG $AWS_ECR_URI:$IMAGE_TAG
          docker push $AWS_ECR_URI:$IMAGE_TAG

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/nest-app nest-app=$AWS_ECR_URI:$IMAGE_TAG
          kubectl rollout status deployment/nest-app

      - name: Verify deployment
        run: |
          kubectl get pods
