name: Deploy to Amazon EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
      IMAGE_TAG: ${{ github.sha }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Generate types from new Prisma schema
        run: npx prisma generate

      - name: Run local tests before building Docker image # <--- Adicionado para rodar testes antes de buildar
        run: npm run test

      - name: Run Prisma migrations in the Kubernetes pod
        run: |
          npx prisma migrate deploy

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $AWS_ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $AWS_ECR_REPOSITORY:$IMAGE_TAG $AWS_ECR_URI:$IMAGE_TAG
          docker push $AWS_ECR_URI:$IMAGE_TAG

      - name: Update kubeconfig for AWS EKS
        run: |
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/nest-app nest-app=$AWS_ECR_URI:$IMAGE_TAG
          kubectl rollout status deployment/nest-app

      - name: Verify deployment
        run: kubectl get pods
